2.42. Разметка всех страниц
htmlacademy-htmlcss/1874477-sedona-36 pull request #2
Opened 2023-01-20 15:36 UTC by sneijder23

2023-01-21 08:21 UTC, Kartaviy-arteom requested changes

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                <img src="#" alt="Иконка поиска">
это декоративная графика, не должна быть в разметке. Можно посмотреть критерий https://up.htmlacademy.ru/htmlcss/36/criteries#IMG-01

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                <p class="favorite-icon-text">12</p>
<p> - для одного слова или цифры очень избыточно, лучше span
img - тут не нужен

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +        <header class="inner-header">
уместней будет использовать section

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <img src="#" alt="Переход на главную">
img лишний

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                    <p class="breadcrumbs-item-text">Гостиницы</p>
в параграфе нет необходимости

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                <fieldset class="catalog-filter-group">
это все форма

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                                <input class="control-input" type="checkbox" name="swimming-pool" checked>
эти чекбоксы это все инфраструктура, у них будет одинаковый name, но разный value

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <li class="catalog-filter-item">
с радио кнопками нужно сделать аналогично. Возможен выбор только одного варианта, сейчас у тебя вместо группы из 3-х радиокнопок, просто 3 радиокнопки

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <input class="control-range-input" type="range" name="price-range" min="0" max="9000" value="7500">
реализация этого элемента будет показана в курсе чуть позже, один input здесь не получится использовать. Пока можно оставить так

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                    <input type="submit" value="Применить">
используй кнопки button, не нужно использовать для этого input это устаревшее решение

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +            <div class="catalog-header">
в помощь в именовании классов тебе поможет https://github.com/yoksel/common-words

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                <select class="select-control" id="sorting" name="sorting">
наверное ты хотел добавить label

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                <img src="#" alt="Сортировка значками">
оставь просто кнопки, img не нужен

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <a class="button-favorites button" href="#">В ИЗБРАННОЕ</a>
тебе не обязательно делать слово заглавными, это можно делать в стилях. Избранное можно кнопкой

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <p class="catalog-item-text">Гостиница</p>
параграфы тут не уместны

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <img class="raiting-stars-icon" src="#" alt="Рейтинг в звездах">
img тут тебе не нужен

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                        <p class="rating-stars-item-text">Рейтинг: 8,5</p>
параграф избыточен

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +        <section class="subscribe subscribe-inner">
можно оставить в main

2023-01-21 08:21 UTC, Kartaviy-arteom commented on catalog.html
> +                  <img src="#" alt="Вконтакте">
img и далее не нужны

2023-01-21 08:21 UTC, Kartaviy-arteom commented on index.html
> +        <a href="index.html" class="logo">
нет смысла делать ссылку саму на себя, на главной можно просто не добавлять атрибут href ссылке
далее аналогично хедеру каталога

2023-01-21 08:21 UTC, Kartaviy-arteom commented on index.html
> +          <img src="#" alt="Sedona">
тебе не нужно 3 картинки, оставь одну

2023-01-21 08:21 UTC, Kartaviy-arteom commented on index.html
> +             <p class="main-header-text">Рассмотрим причины, по которым Седона круче, чем Гранд-Каньон!</p>
причины должны быть в этой секции

2023-01-21 08:21 UTC, Kartaviy-arteom commented on index.html
> +            <li class="reason-item" style="background-image: url(img/photo-1.jpg.jpg)">
это все предыдущая причина, это илюстрация к ней

2023-01-21 08:21 UTC, Kartaviy-arteom commented on index.html
> +            <li class="reason-item" style="background-image: url(img/photo-2.jpg.jpg)">
тебе не нужны инлайновые стили, совсем

2023-01-21 08:21 UTC, Kartaviy-arteom commented on index.html
> +              <img src="#" alt="Каньон, горы">
объединить эту причину с мостом

2023-01-21 11:32 UTC, sneijder23 commented on catalog.html
> +            <div class="catalog-header">
не приходит ничего в голову, я вижу раздел контента - каталог(<section class="catalog">) в котором есть постоянная шапка каталога(<div class="catalog-header">)

2023-01-21 11:33 UTC, sneijder23 commented on catalog.html
> +                <img src="#" alt="Сортировка значками">
можно реализовать через список? и кнопка реализуется через button?

2023-01-21 11:35 UTC, sneijder23 commented on catalog.html
> +                        <a class="button-favorites button" href="#">В ИЗБРАННОЕ</a>
копировал из фигмы раздел контент

2023-01-21 11:45 UTC, sneijder23 commented on catalog.html
> +                        <p class="catalog-item-text">Гостиница</p>
использовать span?

2023-01-22 18:57 UTC, Kartaviy-arteom commented on catalog.html
> +      <section class="catalog">
этой секции не помешал бы заголовок, он будет с классом vissually-hidden, потом добавим стили и его не будет видно на странице

2023-01-22 18:57 UTC, Kartaviy-arteom commented on catalog.html
> +              <button class="button-favorites button">В ИЗБРАННОЕ</button>
кнопкам добавить тип https://developer.mozilla.org/ru/docs/Web/HTML/Element/button

2023-01-23 08:05 UTC, sneijder23 commented on catalog.html
> +      <section class="catalog">
я подумал, что скринридер прочитает label в начале этой секции и поэтому не стал добавлять, исправил.

2023-01-23 08:20 UTC, Kartaviy-arteom commented on catalog.html
> +      <section class="catalog">
там есть быстрая навигация по заголовкам. Так же это важно для поисковой оптимизации. Ты выделяешь секцией важный смысловой блок, а заголовком указываешь его тему. Label это подпись к определенному элементу, не всей секции

2023-01-23 12:39 UTC, merged